Revert "marble defconfig: Enable CONFIG_USER_NS"
This would result in several symbols not protected by KMI being used by
vendor modules, which is unacceptable.

ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
Symbols missing from symbol list:
 - from_kuid_munged
 - init_user_ns
 - make_kgid
 - make_kuid

In the Melt Kernel, the symbol `from_kuid_munged` will be used by
`kernel/msm_sysstats.ko`, and the symbols `init_user_ns`, `make_kgid`,
and `make_kuid` will be used by `techpack/datarmnet-ext/shs/rmnet_shs.ko`.

We will adjust the build script so that CONFIG_USER_NS is enabled only
when compiling the kernel image.

This reverts commit 0115f1d2f5e7350275a635a63ddd6089e9d28826.